#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to the followint requirement:
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# when querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!
# You can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
